import Foundation
import SwiftUI

/// Heuristic categories that flag well-known disk hogs. Each category
/// either matches a directory name (and prunes — we count the directory
/// as one item, not its children) or matches a file extension above a
/// size threshold.
enum InsightCategory: String, CaseIterable, Identifiable {
    case nodeModules         // node_modules
    case gitRepos            // .git
    case buildArtifacts      // build / target / DerivedData / .build / dist / out / .next
    case caches              // any folder whose lowercased name contains "cache"
    case applicationBundles  // *.app
    case largeVideo          // mp4/mov/mkv/etc > 50 MB
    case archivesInstallers  // dmg/iso/zip/tar/gz/pkg/7z/rar > 50 MB
    case largeImages         // raw/heic/jpg/png/tiff > 20 MB
    case logs                // *.log > 5 MB

    var id: String { rawValue }

    var label: String {
        switch self {
        case .nodeModules:        return "node_modules folders"
        case .gitRepos:           return ".git directories"
        case .buildArtifacts:     return "Build artifacts"
        case .caches:             return "Cache folders"
        case .applicationBundles: return "Applications"
        case .largeVideo:         return "Large videos"
        case .archivesInstallers: return "Archives & installers"
        case .largeImages:        return "Large images"
        case .logs:               return "Log files"
        }
    }

    var blurb: String {
        switch self {
        case .nodeModules:        return "Reinstallable npm dependencies. Safe to delete; restored by `npm install`."
        case .gitRepos:           return "Git history. Deleting loses local commits — push first."
        case .buildArtifacts:     return "Build outputs. Regenerated by your build system."
        case .caches:             return "App caches. Regenerated automatically; safe to clear."
        case .applicationBundles: return "Installed apps."
        case .largeVideo:         return "Big media files — back up before deleting."
        case .archivesInstallers: return "DMGs, ZIPs, and installers you may have already used."
        case .largeImages:        return "Raw photos, full-resolution exports, scans."
        case .logs:               return "Application log files. Usually safe to delete."
        }
    }

    var icon: String {
        switch self {
        case .nodeModules:        return "shippingbox.fill"
        case .gitRepos:           return "arrow.triangle.branch"
        case .buildArtifacts:     return "hammer.fill"
        case .caches:             return "internaldrive.fill"
        case .applicationBundles: return "app.fill"
        case .largeVideo:         return "film.fill"
        case .archivesInstallers: return "archivebox.fill"
        case .largeImages:        return "photo.fill"
        case .logs:               return "doc.text.fill"
        }
    }

    var tint: Color {
        switch self {
        case .nodeModules:        return .orange
        case .gitRepos:           return .purple
        case .buildArtifacts:     return .red
        case .caches:             return .blue
        case .applicationBundles: return .indigo
        case .largeVideo:         return .pink
        case .archivesInstallers: return .yellow
        case .largeImages:        return .teal
        case .logs:               return .gray
        }
    }
}

struct InsightHit: Identifiable {
    let id = UUID()
    let category: InsightCategory
    let url: URL
    let size: Int64
    let isDirectory: Bool
}

struct InsightSummary: Identifiable {
    let id: String
    let category: InsightCategory
    let totalSize: Int64
    let count: Int
    /// Full deduplicated list, sorted descending by size. The card view
    /// shows only the first 3; the detail sheet shows everything.
    let items: [InsightHit]
}

enum InsightDetector {
    private static let buildArtifactNames: Set<String> = [
        "DerivedData", "build", "Build",
        "target", ".build",
        "dist", "out", ".next", ".nuxt", ".parcel-cache",
        "__pycache__", ".pytest_cache",
    ]
    private static let videoExts: Set<String>    = ["mp4","mov","mkv","avi","wmv","flv","m4v","webm","mpg","mpeg"]
    private static let archiveExts: Set<String>  = ["zip","tar","gz","tgz","dmg","iso","pkg","7z","rar","xz","bz2","tar.gz"]
    private static let imageExts: Set<String>    = ["jpg","jpeg","png","heic","raw","tiff","tif","cr2","nef","arw","dng","psd"]
    private static let logExts: Set<String>      = ["log"]

    static func detect(root: FileNode) -> [InsightSummary] {
        var hits: [InsightHit] = []
        walk(node: root, into: &hits)

        var bucket: [InsightCategory: [InsightHit]] = [:]
        for h in hits { bucket[h.category, default: []].append(h) }

        var summaries: [InsightSummary] = []
        for (cat, items) in bucket {
            let sorted = items.sorted { $0.size > $1.size }
            // Dedup by URL path — keep the first (largest) of any duplicates.
            // Defensive: if the same path ever reaches the bucket twice it
            // shows as a doubled row in the category card.
            var seenPaths = Set<String>()
            let unique = sorted.filter { seenPaths.insert($0.url.path).inserted }
            let total = unique.reduce(Int64(0)) { $0 + $1.size }
            summaries.append(InsightSummary(
                id: cat.rawValue,
                category: cat,
                totalSize: total,
                count: unique.count,
                items: unique
            ))
        }
        return summaries.sorted { $0.totalSize > $1.totalSize }
    }

    private static func walk(node: FileNode, into hits: inout [InsightHit]) {
        // Application bundles come through as "files" because Scanner
        // collapses .isPackage. Catch them here at the leaf level.
        if !node.isDirectory && node.url.pathExtension.lowercased() == "app" {
            hits.append(.init(category: .applicationBundles, url: node.url,
                              size: node.size, isDirectory: false))
            return
        }

        if node.isDirectory {
            // Whole-directory categories — record once and stop recursing
            // so we don't double-count their interior files.
            switch node.name {
            case "node_modules":
                if node.size > 0 {
                    hits.append(.init(category: .nodeModules, url: node.url,
                                      size: node.size, isDirectory: true))
                }
                return
            case ".git":
                if node.size > 0 {
                    hits.append(.init(category: .gitRepos, url: node.url,
                                      size: node.size, isDirectory: true))
                }
                return
            default:
                break
            }
            if buildArtifactNames.contains(node.name) {
                if node.size > 0 {
                    hits.append(.init(category: .buildArtifacts, url: node.url,
                                      size: node.size, isDirectory: true))
                }
                return
            }
            // Don't catch the literal "Caches" root inside ~/Library — too broad.
            if node.name.lowercased().contains("cache") && node.size > 1_000_000 {
                hits.append(.init(category: .caches, url: node.url,
                                  size: node.size, isDirectory: true))
                return
            }
        } else {
            // File-level categories
            let ext = node.fileExtension
            if videoExts.contains(ext), node.size > 50_000_000 {
                hits.append(.init(category: .largeVideo, url: node.url,
                                  size: node.size, isDirectory: false))
            } else if archiveExts.contains(ext), node.size > 50_000_000 {
                hits.append(.init(category: .archivesInstallers, url: node.url,
                                  size: node.size, isDirectory: false))
            } else if imageExts.contains(ext), node.size > 20_000_000 {
                hits.append(.init(category: .largeImages, url: node.url,
                                  size: node.size, isDirectory: false))
            } else if logExts.contains(ext), node.size > 5_000_000 {
                hits.append(.init(category: .logs, url: node.url,
                                  size: node.size, isDirectory: false))
            }
        }

        node.children?.forEach { walk(node: $0, into: &hits) }
    }
}

// MARK: - Top items helper

enum TopItems {
    /// Largest nodes anywhere in the tree, excluding the root itself.
    ///
    /// Dedupes by ancestry: if an ancestor of a candidate is already in
    /// the result, the candidate is skipped. Without this, a directory
    /// and its single dominant child both rank near the top and look
    /// like duplicate rows (since a directory's size = sum of its
    /// children, so size(parent) >= size(child) and they appear next to
    /// each other when sorted by size). Walking size-desc means
    /// ancestors are always considered before their descendants, so a
    /// simple "skip if any ancestor included" rule is sufficient.
    static func find(root: FileNode, count: Int = 10) -> [FileNode] {
        var all: [FileNode] = []
        all.reserveCapacity(2048)
        func visit(_ n: FileNode) {
            if n !== root { all.append(n) }
            n.children?.forEach(visit)
        }
        visit(root)

        let sorted = all.sorted { $0.size > $1.size }

        var result: [FileNode] = []
        var includedIDs = Set<ObjectIdentifier>()
        for node in sorted {
            // Walk parent chain — if any ancestor is already in the
            // result, this node is "inside" something we already showed.
            var ancestor = node.parent
            var skip = false
            while let a = ancestor {
                if includedIDs.contains(ObjectIdentifier(a)) {
                    skip = true
                    break
                }
                ancestor = a.parent
            }
            if skip { continue }
            result.append(node)
            includedIDs.insert(ObjectIdentifier(node))
            if result.count >= count { break }
        }
        return result
    }

    static func countDirectories(root: FileNode) -> Int {
        var n = 0
        func visit(_ node: FileNode) {
            if node.isDirectory { n += 1 }
            node.children?.forEach(visit)
        }
        visit(root)
        return n
    }
}
